Feature/evaluation command
pvs-hd-tea/PyTypes pull request #183
Opened 2022-08-23 15:05 UTC by RecurvedBow

2022-08-23 15:59 UTC, bengsparks requested changes

2022-08-23 15:59 UTC, bengsparks commented on typegen/evaluation/__init__.py
> +def _get_changed_file_paths(original_root_folder_path, traced_root_folder_path, potential_changed_files_relative_paths):
Add type hints to this file please.

2022-08-23 15:59 UTC, bengsparks commented on typegen/evaluation/file_type_hints_collector.py
> +    def _get_annotation_value_of_attribute(self, annotation: cst.Attribute, add_full_module_name: bool =True) -> str:
Formatting

2022-08-23 16:55 UTC, RecurvedBow commented on typegen/evaluation/file_type_hints_collector.py
> +    def _get_annotation_value_of_attribute(self, annotation: cst.Attribute, add_full_module_name: bool =True) -> str:
Fixed

2022-08-23 16:55 UTC, RecurvedBow commented on typegen/evaluation/__init__.py
> +def _get_changed_file_paths(original_root_folder_path, traced_root_folder_path, potential_changed_files_relative_paths):
Added

2022-08-24 09:57 UTC, bengsparks approved these changes

2022-08-24 10:00 UTC, merged