Feature/trace class functions
pvs-hd-tea/PyTypes pull request #33
Opened 2022-06-01 18:53 UTC by RecurvedBow

2022-06-02 09:14 UTC, bengsparks requested changes

2022-06-02 09:14 UTC, bengsparks commented on tests/test_tracer.py
> +        "tests/test_tracer.py",
Use str and pathlib to correctly build the path for your tests

2022-06-03 14:24 UTC, bengsparks requested changes

2022-06-03 14:24 UTC, bengsparks commented on tracing/tracer.py
> +        first_element_name = list(frame.f_locals)[0]
@RecurvedBow this still needs to be reviewed.

2022-06-03 16:03 UTC, RecurvedBow commented on tracing/tracer.py
> +        first_element_name = list(frame.f_locals)[0]
Not sure what benefit this change has, but okay

2022-06-03 16:05 UTC, merged